
args_count = {'documentclass':(1, 1),
              'usepackage':(1, 1),
              'title':(1, 0),
              'author':(1, 0),
              'date':(1, 0),
              'color':(1, 0),
              'input':(1, 0),
              'part':(1, 0),
              'chapter':(1, 1),
              'section':(1, 1),
              'subsection':(1, 1),
              'subsubsection':(1, 1),
              'paragraph':(1, 1),
              'subparagraph':(1, 1),
              'chapter*':(1, 1),
              'section*':(1, 1),
              'subsection*':(1, 1),
              'subsubsection*':(1, 1),
              'paragraph*':(1, 1),
              'subparagraph*':(1, 1),
              'setcounter':(2, 0),
              'addcontentsline':(3, 0),
              'linespread':(1, 0),
              'mbox':(1, 0),
              'hyphenation':(1, 0),
              'todo':(1, 0),
              'begin':(1, 0),
              'end':(1, 0),
              'emph':(1, 0),
              'renewcommand':(2, 0),
              'left':(1, 0),
              'right':(1, 0),
              'verb':(1, 0),
              'frac':(2, 0),
              'textsubscript':(1, 0),
              'textsuperscript':(1, 0),
              'hspace':(1, 0),
              'vspace':(1, 0),
              'setlength':(2, 0),
              'textcolor':(2, 0),
              'pagecolor':(1, 0),
              'colorbox':(2, 0),
              'fcolorbox':(3, 0),
              'textit':(1, 0),
              'textbf':(1, 0),
              'textrm':(1, 0),
              'textsf':(1, 0),
              'texttt':(1, 0),
              'textup':(1, 0),
              'textsl':(1, 0),
              'textsc':(1, 0),
              'textmd':(1, 0),
              'textlf':(1, 0),
              'upperaces':(1, 0),
              'underline':(1, 0),
              'textnormal':(1, 0),
              'emph':(1, 0),
              'fontsize':(2, 0),
              'setmainfont':(1, 1),
              'setsansfont':(1, 1),
              'addfontfeatures':(1, 0),
              'item': (0,1),
              'inputencoding': (1,0),
              'url':(1,0),
              'hat':(1, 0),
              'widehat':(1, 0),
              'check':(1, 0),
              'tilde':(1, 0),
              'widetilde':(1, 0),
              'acute':(1, 0),
              'grave':(1, 0),
              'dot':(1, 0),
              'ddot':(1, 0),
              'breve':(1, 0),
              'bar':(1, 0),
              'vec':(1, 0),
              'resizebox':(3,0),
              'scalebox':(2,0),
              'cline':(1,0),
              'cellcolor':(1,1),
              'caption':(1,0),
              'includegraphics':(1,1),
              'sqrt':(1,1),
              'mathrm':(1,0),
              'substack':(1,0),
              }

env_opts = {'figure': (0, 1),
            'array': (1, 1),
            'minipage': (2, 0),
            'tabular': (1, 1),
            'spacing':(1, 0),
            'turn':(1, 0),
            'rotate':(1, 0),
            'table':(0, 1),
            'wrapfigure':(2, 0),
            'subfigure':(1, 1),}

shortcuts = [('\\-', '\u00AD'),
             ('---', '\u2014'),
             ('~', '\u00A0'),
             ('"=', '\u2010')]

verb_tags = ['verb']
verb_envs = ['verbatim', 'alltt', 'lstlisting', 'listing'] 
